### ISSUE TITLE
Change Output filename

### ISSUE THREAD

**Issue by smithandrewl** [smithandrewl/py_process_graph#4]
The name of the produced file should be of the format `process_graph_<timestamp>` where `<timestamp>` is an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) formatted date.

Example:

`process_graph_2013-04-01T13-01-02.png`

**Comment by taimooralqureshi** [comment]
please assign this issue to me!

**Comment by smithandrewl** [comment]
It is yours
